#version: '3.8'

services:
  db-postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - last-filter

  last-filter:
    build:
      context: ./last-filter
    container_name: filtro
    ports:
      - "3003:3003"
    environment:
      POSTGRES_HOST: db-postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - db-postgres
    env_file:
      - ./.env
    volumes:
      - ./last-filter:/app
      - /app/node_modules
    networks:
      - last-filter  

networks:
  last-filter:  
    driver: bridge
